[phases.setup]
nixPkgs = ["php83", "composer", "nodejs_20", "npm"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache",
    "rm -rf vendor",
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm install",
    "npm run build",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan optimize"
]


